### PR TITLE
Switch metadata fetching to API

### LINKED ISSUE #2: Support metadata fetching
When the CCM code was still integrated into Kubernetes, it was possible to fetch node metadata from kubelet running on the nodes.

With the separated CCM, this is no longer possible.
Modify [cloudstack.go](https://github.com/swisstxt/cloudstack-cloud-controller-manager/blob/master/cloudstack.go#L95-L106) to support fetching metadata via the Cloudstack API, if possible.

### PR DESCRIPTION
**Pull request by onitake**
This PR removes old code that fetches metdata from DHCP, which only works when running inside kubelet.

With external CCMs, this is no longer relevant. All metadata should be fetched from the Cloudstack API.

Fixes #2 .

### CODE REVIEW

**Review by joschi36 — APPROVED** [review]
Looks nice, I test it as soon as I‘m back from smoking!

**Comment by onitake** [comment]
It looks like metadata fetching works, but no labels are assigned to nodes.
Further investigation is needed.

The logs mention this repeatedly:
```
node_controller.go:329] This node xxxx is registered without the cloud taint. Will not process.
```

Either we need to default-taint nodes in kubelet (perhaps there's a command line option?) when they launch for the first time or figure out a way to reliably identify Cloudstack instances in the CCM.

**Comment by onitake** [comment]
As explained in the README now, label assignment *does* work - but it only happens when a node is tainted as being "uninitialized". This is not the case for existing nodes. I have yet to try and see what happens when adding a new node.

Perhaps adding the
```
--register-with-taints=node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
```
to the kubelet command line is necessary.

It is easy to re-trigger label assignment though: Simply set the uninitialized taint and the CloudStack CCM will do its magic.

The warning message printed above can be ignored, it is just debug noise and was already shunted off in the k8s code base: https://github.com/kubernetes/kubernetes/pull/65981

**Comment by onitake** [comment]
Looks like it will no longer build when basing on k8s 1.14-alpha.0, due to the old cloud provider code being compiled into the controller. I'll re-add the dependencies, they should go away automatically with `go mod tidy` once the cloud providers have been removed.

**Comment by onitake** [comment]
Documentation is updated and the CCM is tested, merging this now.

**Pull request merged**
